### PR TITLE
Upate dependencies

### PR DESCRIPTION
**Pull request by VuiMuich**
Fixes deprecation warning for using quick-xml 0.22.0

Changes proposed in this pull request:
- always use latest patch version of anyhow 1.0.x
- use stable version of xcb

### CODE REVIEW

**Comment by VuiMuich** [comment]
Also I would like to request a version bump if this gets merged, as I noticed the deprecation warning when attempting to package gobble for nixpkgs.
I would like to open a PR for on nixos/nixpkgs once this can compile without having to worry to require any patch for the package too soon.

**Comment by EmperorPenguin18** [comment]
When I try to build your fork I get this error:
```
...
Compiling xcb v1.2.2
error[E0658]: use of unstable library feature 'array_methods'
   --> /home/sebastien/.cargo/registry/src/github.com-1ecc6299db9ec823/xcb-1.2.2/src/lat1_str.rs:227:39
    |
227 |         Lat1Str::from_bytes(self.data.as_slice())
    |                                       ^^^^^^^^
    |
    = note: see issue #76118 <https://github.com/rust-lang/rust/issues/76118> for more information
    = help: add `#![feature(array_methods)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `xcb` due to previous error
```

**Comment by VuiMuich** [comment]
Oops, sorry, I messed up my testbuild and built it again against the stable tag completely ignoring the output :see_no_evil: 

I'll try to come up with a fix in the next days.

**Comment by VuiMuich** [comment]
Man, that was a lot of api changes in xcb.
It builds again, but the terminal window is not becoming mapped again.

**Comment by VuiMuich** [comment]
Looks like for some reason, when we kill the child now, we also kill the parent :frowning_face:

**Comment by VuiMuich** [comment]
Now everything seems working.
Only thing I am not certain about is if the `overlymode` works correct, as I am using `leftwm` in which I have to force the new window into floating mode with some window rule, but I believe this also enforces xyhw for the window.

**Comment by EmperorPenguin18** [comment]
> Now everything seems working. Only thing I am not certain about is if the `overlymode` works correct, as I am using `leftwm` in which I have to force the new window into floating mode with some window rule, but I believe this also enforces xyhw for the window.

Overlay mode doesn't work for tilers in my experience. I'll test it on my system.

**Comment by EmperorPenguin18** [comment]
I'm still failing to build. Are you using the makefile? I don't really know how to use cargo so I'm probably messing something up.

**Comment by VuiMuich** [comment]
🤔 what rustversion are you using? I use latest stable, which is 1.71.1 iirc (currently not on my machine).

Actually I build with the nix expression that builds the package, as I am on NixOS am learning how to package for the nixpkgs repo.
I got errors using the makefile myself, so I replicated those steps in nix. But now that you mention that the makefile fails for you, it might actually be that it was the broken api for me and not missing deps in my build env as I suspected all along.
I'll test this asap.

**Comment by VuiMuich** [comment]
Are you possibly building with a `nightly` rust? `cargo msrv --min 1.60.0` reports all fine...

**Comment by EmperorPenguin18** [comment]
Okay with that last commit it builds. Seems it breaks overlap mode so give me a bit to figure that out.

**Comment by EmperorPenguin18** [comment]
Okay I figured it out. I am going to merge, but let me do a couple things before I make a release.

Also thanks so much for doing this! I've wanted to update to the stable xcb since I got a dependabot alert about it.

**Comment by VuiMuich** [comment]
Thanks for the merge!

Just ping me, when you do the new release.

**Pull request merged**
